
import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import { Spinner } from '../ui/icons';

const MrBeatboxTab: React.FC = () => {
    const [plan, setPlan] = useState('');
    const [isLoading, setIsLoading] = useState(true);

    const fetchPlan = async () => {
        setIsLoading(true);
        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
            const prompt = `
            Based on the following user idea, generate a high-level, structured project plan for creating an AI called "Mr. BeatBox". 
            Format the response as markdown. The plan should be detailed enough for a technical audience but still readable.
            
            User Idea:
            "Build a TensorFlow neural network where piano notes and IPA phoneme symbols are learned. The AI should learn to mimic me and then create its own music. It should be a duet partner or perform solo with multiple layers (e.g., beatbox, piano, trumpet, guitar). The AI should learn from watching video, listening to audio, and reading sheet music. The app needs inputs for all these data types."
            
            Structure the plan with these sections:
            1.  **Project Overview & Goals:** A brief summary.
            2.  **Core AI/ML Architecture:** Describe the models (e.g., Transformers, GANs, etc.) and data processing.
            3.  **Data Acquisition & Preprocessing:** Detail the types of data needed and how to process them (video, audio, MIDI/sheet music).
            4.  **Training Phases:** Outline a multi-stage training strategy (e.g., foundational rhythm, melodic mimicry, compositional generation).
            5.  **Application Front-End:** Describe the necessary UI components for interaction.
            6.  **Key Challenges:** List potential technical hurdles.
            `;
            
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-pro',
                contents: prompt,
            });
            setPlan(response.text);
        } catch (error) {
            console.error("Failed to generate project plan:", error);
            setPlan("Could not generate the project plan. Please check your API key and network connection.");
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        fetchPlan();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const renderPlan = (markdownText: string) => {
        const lines = markdownText.split('\n');
        return lines.map((line, index) => {
            if (line.startsWith('### ')) {
                return <h3 key={index} className="text-lg font-semibold mt-4 mb-2 text-cyan-300">{line.substring(4)}</h3>;
            }
            if (line.startsWith('## ')) {
                return <h2 key={index} className="text-xl font-bold mt-6 mb-3 text-cyan-400">{line.substring(3)}</h2>;
            }
            if (line.startsWith('**')) {
                const parts = line.split('**');
                return <p key={index} className="mb-2"><strong className="text-gray-100">{parts[1]}</strong>{parts[2]}</p>
            }
            if (line.startsWith('* ')) {
                return <li key={index} className="ml-6 list-disc">{line.substring(2)}</li>;
            }
            return <p key={index} className="mb-2">{line}</p>;
        });
    };

    return (
        <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-white mb-3">Project: Mr. BeatBox - The AI Duet Partner</h2>
            <p className="text-gray-400 mb-6">
                This is a conceptual outline for an ambitious AI music project. The following plan was generated by Gemini 2.5 Pro to structure the development of a real-time, learning-based musical partner.
            </p>

            <div className="bg-gray-800/50 p-6 rounded-lg">
                {isLoading ? (
                    <div className="flex flex-col items-center justify-center h-64">
                        <Spinner className="w-10 h-10 mb-4" />
                        <p className="text-gray-300">Generating project plan with Gemini Pro...</p>
                    </div>
                ) : (
                    <div className="prose prose-invert max-w-none text-gray-300">
                        {renderPlan(plan)}
                    </div>
                )}
            </div>
            
            <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-gray-800 p-4 rounded-lg text-center opacity-50">
                    <h4 className="font-semibold mb-2">Upload Audio/Video</h4>
                    <p className="text-sm text-gray-400">(Conceptual UI)</p>
                    <button disabled className="mt-2 w-full bg-gray-600 text-white font-semibold py-2 px-4 rounded-lg cursor-not-allowed">
                        Select Files
                    </button>
                </div>
                <div className="bg-gray-800 p-4 rounded-lg text-center opacity-50">
                    <h4 className="font-semibold mb-2">Load Sheet Music</h4>
                    <p className="text-sm text-gray-400">(Conceptual UI)</p>
                    <button disabled className="mt-2 w-full bg-gray-600 text-white font-semibold py-2 px-4 rounded-lg cursor-not-allowed">
                        Import MIDI/XML
                    </button>
                </div>
                <div className="bg-gray-800 p-4 rounded-lg text-center opacity-50">
                    <h4 className="font-semibold mb-2">Start Training</h4>
                    <p className="text-sm text-gray-400">(Conceptual UI)</p>
                    <button disabled className="mt-2 w-full bg-cyan-800 text-white font-semibold py-2 px-4 rounded-lg cursor-not-allowed">
                        Begin Learning
                    </button>
                </div>
            </div>
        </div>
    );
};

export default MrBeatboxTab;
